Bug Fix - Change Gconnect method to support users with Flask version(0.10.1)
The application was originally written Flask version 0.9 and as a consequence
users would get the following error message when using their Google account
while running Flask version 0.10.1

10.0.2.2 - - [28/Oct/2015 08:42:27] "GET /login HTTP/1.1" 200 -
TypeError: <oauth2client.client.OAuth2Credentials object at 0xb5c612cc> is not JSON serializable

The reason for this behavior can be found in this stackoverflow post

"http://stackoverflow.com/questions/22915461/google-login-server-side-flow-"
"storing-credentials-python-examples/22930708#22930708"